# Generated by Django 3.1.6 on 2021-03-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
