# Generated by Django 3.1.6 on 2021-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('task_no', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=500)),
            ],
        ),
    ]
