# Generated by Django 3.1.6 on 2021-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_todomodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='deadline',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
