# Generated by Django 3.1.6 on 2021-03-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_todomodel_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='note',
            field=models.CharField(default='Null', max_length=150),
        ),
    ]
