# Generated by Django 3.1.6 on 2021-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_todomodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='user',
        ),
    ]
