# Generated by Django 3.1.6 on 2021-03-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20210328_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileModel',
        ),
    ]
