# Generated by Django 3.1.6 on 2021-03-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_delete_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='uid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='task_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
