# Generated by Django 3.1.6 on 2021-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20210329_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
