# Generated by Django 3.1.6 on 2021-03-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20210329_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='task_no',
        ),
    ]
